import { describe, it, expect, vi } from 'vitest';
import { DocumentGenerator } from '../../src/generation/document-generator.js';
import { LLMWrapper } from '../../src/utils/llm-wrapper.js';
import { TemplateSystem } from '../../src/generation/template-system.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';

describe('DocumentGenerator Persona Selection', () => {
  const mockLLM = {
    generate: vi.fn().mockResolvedValue('## Section Title\nContent'),
  } as unknown as LLMWrapper;

  const mockTemplateSystem = {
    getTemplate: vi.fn(),
  } as unknown as TemplateSystem;

  const mockStore = {} as unknown as WorkspaceStore;

  const generator = new DocumentGenerator(mockLLM, mockTemplateSystem, mockStore);

  it('selects Product Manager persona for PRD', async () => {
    const prdTemplate = {
      documentId: 'PRD',
      name: 'Product Requirements Document',
      version: '1.0',
      metadata: { primaryOwner: 'Product Manager' },
      sections: [{ id: 's1', title: 'Section Title' }],
      promptHints: {},
    };

    // @ts-ignore - access private method for testing
    const prompt = generator['buildSystemPrompt'](prdTemplate);
    expect(prompt).toContain('elite Staff Product Manager');
    expect(prompt).toContain('Generated by | Docxa (Expert Mode: Product Manager)');
  });

  it('selects DevOps Engineer persona for NFR', async () => {
    const nfrTemplate = {
      documentId: 'NFR',
      name: 'Non-Functional Requirements',
      version: '1.0',
      metadata: { primaryOwner: 'DevOps Engineer' },
      sections: [{ id: 's1', title: 'Section Title' }],
      promptHints: {},
    };

    // @ts-ignore - access private method for testing
    const prompt = generator['buildSystemPrompt'](nfrTemplate);
    expect(prompt).toContain('Staff Site Reliability Engineer (SRE)');
    expect(prompt).toContain('Generated by | Docxa (Expert Mode: DevOps Engineer)');
  });

  it('falls back to Solution Architect for unknown owners', async () => {
    const unknownTemplate = {
      documentId: 'ABC',
      name: 'ABC Document',
      version: '1.0',
      metadata: { primaryOwner: 'Unknown' },
      sections: [{ id: 's1', title: 'Section Title' }],
      promptHints: {},
    };

    // @ts-ignore - access private method for testing
    const prompt = generator['buildSystemPrompt'](unknownTemplate);
    expect(prompt).toContain('Solutions Architect');
  });
});
