import { LLMWrapper } from '../utils/llm-wrapper.js';
import { TemplateSystem } from './template-system.js';
import { Document, DocumentType, DocumentSection } from '../models/document-model.js';
import { WorkspaceStore } from '../storage/workspace-store.js';
import { DocumentTemplate, TemplateSection } from './template-schema.js';
import crypto from 'crypto';

export class DocumentGenerator {
  private llm: LLMWrapper;
  private templateSystem: TemplateSystem;
  private store: WorkspaceStore;

  constructor(llm: LLMWrapper, templateSystem: TemplateSystem, store: WorkspaceStore) {
    this.llm = llm;
    this.templateSystem = templateSystem;
    this.store = store;
  }

  async generate(type: string, context: any): Promise<Document> {
    const template = this.templateSystem.getTemplate(type);
    if (!template) throw new Error(`Template for ${type} not found`);

    // Check dependencies (soft check for now)
    /*
        for (const dep of template.dependencies) {
            // Future: check if dependency document exists in store
        }
        */

    const systemPrompt = this.buildSystemPrompt(template);
    const userPrompt = this.buildUserPrompt(template, context);

    const rawResponse = await this.llm.generate(userPrompt, systemPrompt);
    const sections = this.parseSections(rawResponse, template.sections);

    return {
      type: type.toUpperCase() as DocumentType,
      version: template.version,
      status: 'draft',
      sections,
      dependencies: template.dependencies as DocumentType[],
      metadata: {
        templateVersion: template.version,
        generatedAt: new Date().toISOString(),
      },
      lastUpdated: new Date().toISOString(),
    };
  }

  private getPersonaForOwner(owner: string): string {
    const PERSONA_MAPPINGS: Record<string, string> = {
      'Product Manager':
        'elite Staff Product Manager and Product Strategist with 20+ years of experience in translating business vision into detailed product requirements',
      'Solution Architect':
        'Staff Solutions Architect and Systems Designer specialized in high-level technical mapping and architectural constraints',
      'Business Stakeholder':
        'Principal Business Consultant and Enterprise Architect focused on high-level business value, ROI, and organizational impact',
      'Engineering Lead':
        'Staff Software Engineer and Technical Lead with deep expertise in implementation detail, code structure, and low-level design',
      'DevOps Engineer':
        'Staff Site Reliability Engineer (SRE) and DevOps Expert focused on infrastructure, performance, security, and scalability',
    };

    return (
      PERSONA_MAPPINGS[owner] ||
      'elite Staff Software Engineer and Solutions Architect with 20+ years of experience'
    );
  }

  private buildSystemPrompt(template: DocumentTemplate): string {
    const hints = template.promptHints || ({} as any);
    const owner = template.metadata?.primaryOwner || 'Solution Architect';
    const persona = this.getPersonaForOwner(owner);

    return `You are an ${persona}.
Your goal is to generate a world-class, professional ${template.name} (${template.documentId}) based on repository evidence and functional requirements.

CRITICAL QUALITY REQUIREMENTS:
1. STRUCTURE: Use formal hierarchical numbering (e.g., 1., 1.1, 1.1.1).
2. TONE: Authoritative, precise, and technical. Avoid conversational filler or introductory "Here is your document..." text. Output ONLY the markdown content.
3. SPECIFICITY: You MUST use the provided technical evidence (versions, file paths, build scripts, frameworks) detected in the codebase. Do not generalize if specific evidence is provided.
4. METADATA: Start the document with a professional Markdown table containing:
   | Field | Value |
   | :--- | :--- |
   | Document | ${template.name} |
   | Version | ${template.version} |
   | Date | ${new Date().toISOString().split('T')[0]} |
   | Status | Draft |
   | Generated by | Docxa (Expert Mode: ${owner}) |

5. VALIDATION: Ensure the content aligns perfectly with the FRD and HLD if provided.
6. NO HALLUCINATION: If evidence is missing for a section, provide a high-quality technical placeholder or assumption based on industry best practices, but mark it clearly as [TBD] or [ASSUMPTION].

System Goal: ${hints.systemIntent || `Generate expert-level ${template.name}.`}

Rules for this document type:
${(hints.rules || []).map((r: string) => `- ${r}`).join('\n')}

MUST DO:
${(hints.mustDo || []).map((r: string) => `- ${r}`).join('\n')}

MUST NOT DO:
${(hints.mustNotDo || []).map((r: string) => `- ${r}`).join('\n')}

Format your response as clean markdown. Use ## Section Title exactly as provided.
Do not include a table of contents, intro or outro text. Start directly with the metadata table.
`;
  }

  private buildUserPrompt(template: DocumentTemplate, context: any): string {
    let prompt = `PROJECT CONTEXT:
Project Name: ${context.projectName}
${context.interviewSummaries ? `Interview Summaries: ${context.interviewSummaries}` : ''}
${context.additionalContext ? `Additional Context: ${JSON.stringify(context.additionalContext, null, 2)}` : ''}

EVIDENCE FOR GENERATION:
`;

    if (context.upstreamDocs && Object.keys(context.upstreamDocs).length > 0) {
      prompt += `UPSTREAM DOCUMENTS:\n`;
      for (const [id, content] of Object.entries(context.upstreamDocs)) {
        prompt += `--- ${id} ---\n${content}\n`;
      }
    }

    if (context.interviewSessions && context.interviewSessions.length > 0) {
      prompt += `INTERVIEW SESSIONS:\n`;
      for (const session of context.interviewSessions) {
        prompt += `Role: ${session.roleId}\nAnswers:\n`;
        for (const answer of session.answers) {
          if (answer.normalizedAnswer !== undefined) {
            prompt += `- QuestionId: ${answer.questionId}\n  Answer: ${JSON.stringify(answer.normalizedAnswer)}\n`;
          }
        }
      }
    }

    if (context.repositoryAnalysis) {
      const ra = context.repositoryAnalysis;
      prompt += `REPOSITORY ANALYSIS:\n`;
      prompt += `- Languages: ${ra.languages.join(', ')}\n`;
      prompt += `- Frameworks: ${ra.frameworks.join(', ')}\n`;
      prompt += `- Services: ${ra.services.join(', ')}\n`;
      prompt += `- Monorepo: ${ra.isMonorepo ? 'Yes' : 'No'}\n`;
      prompt += `- Architecture: ${ra.architecture.pattern}\n`;
      prompt += `- Architecture Reasoning: ${ra.architecture.reasoning}\n`;

      if (ra.configContents && Object.keys(ra.configContents).length > 0) {
        prompt += `\nCONFIGURATION FILES EVIDENCE:\n`;
        for (const [file, content] of Object.entries(ra.configContents)) {
          prompt += `--- ${file} ---\n${content}\n`;
        }
      }
    }

    prompt += `\nPlease generate content for the following sections:\n\n`;

    for (const section of template.sections) {
      prompt += `## ${section.title}\n`;
      prompt += `ID: ${section.id}\n`;
      prompt += `PURPOSE: ${section.purpose || section.description || ''}\n`;
      if (section.guidance?.length) {
        prompt += `GUIDANCE:\n${section.guidance.map((g: string) => `- ${g}`).join('\n')}\n`;
      }
      prompt += `\n`;
    }

    return prompt;
  }

  private parseSections(
    rawResponse: string,
    templateSections: TemplateSection[],
  ): DocumentSection[] {
    const sections: DocumentSection[] = [];
    const lines = rawResponse.split('\n');

    let currentSection: Partial<DocumentSection> | null = null;
    let currentContent: string[] = [];

    const flushSection = () => {
      if (currentSection && currentSection.title) {
        sections.push({
          id: currentSection.id || crypto.randomUUID(),
          title: currentSection.title,
          content: currentContent.join('\n').trim(),
          provenance: {
            source: 'generated',
            timestamp: new Date().toISOString(),
            reasoning: 'Generated from template and LLM prompt.',
          },
        });
      }
    };

    for (const line of lines) {
      if (line.startsWith('## ')) {
        flushSection();
        const title = line.replace('## ', '').trim();
        const templateMatch = templateSections.find(
          (s) => s.title.toLowerCase() === title.toLowerCase(),
        );

        currentSection = {
          id: templateMatch?.id || crypto.randomUUID(),
          title: templateMatch?.title || title,
        };
        currentContent = [];
      } else if (currentSection) {
        // Skip metadata lines often generated by LLM if they repeat the prompt structure
        if (
          !line.startsWith('ID: ') &&
          !line.startsWith('PURPOSE: ') &&
          !line.startsWith('GUIDANCE:')
        ) {
          currentContent.push(line);
        }
      }
    }
    flushSection();

    // If no sections were parsed, fallback to a single block (very unlikely if LLM followed instructions)
    if (sections.length === 0) {
      sections.push({
        id: crypto.randomUUID(),
        title: 'Document Content',
        content: rawResponse,
        provenance: {
          source: 'generated',
          timestamp: new Date().toISOString(),
          reasoning: 'Parsing failed, returning raw response.',
        },
      });
    }

    return sections;
  }
}
